name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r backend/requirements.txt

      - name: Run pytest (with coverage)
        env:
          # minimal env so app can start in tests without leaking secrets
          SECRET_KEY: dummy_secret_for_ci
          TESTING: "True"
          DEBUG: "False"
        run: |
          . venv/bin/activate
          pytest --maxfail=1 --disable-warnings --cov=backend --cov-report=term-missing
